// netlify/functions/auth-welcome-email.ts
import { Handler } from '@netlify/functions';
import { createClient } from '@supabase/supabase-js';
import { EmailService } from './shared/emailService';
import { emailTemplates } from './shared/emailTemplates';

const handler: Handler = async (event, context) => {
  // Only allow POST requests
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
      },
      body: JSON.stringify({ error: 'Method not allowed' }),
    };
  }

  try {
    // Parse the webhook payload from Supabase Auth
    const payload = JSON.parse(event.body || '{}');
    
    // Validate webhook signature (optional but recommended)
    const authSignature = event.headers['authorization'];
    const expectedSignature = process.env.SUPABASE_AUTH_WEBHOOK_SECRET;
    
    if (expectedSignature && authSignature !== `Bearer ${expectedSignature}`) {
      console.error('Invalid webhook signature');
      return {
        statusCode: 401,
        body: JSON.stringify({ error: 'Unauthorized' }),
      };
    }

    // Extract user data from the payload
    const { type, table, record, old_record } = payload;
    
    // Only process new user signups
    if (type !== 'INSERT' || table !== 'users') {
      return {
        statusCode: 200,
        body: JSON.stringify({ message: 'Event ignored' }),
      };
    }

    const user = record;
    if (!user || !user.email) {
      console.error('No user email found in payload');
      return {
        statusCode: 400,
        body: JSON.stringify({ error: 'No user email found' }),
      };
    }

    // Initialize services
    const supabase = createClient(
      process.env.SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );
    
    const emailService = new EmailService(process.env.RESEND_API_KEY!);

    // Get or create user profile to get the name
    let userName = user.email.split('@')[0]; // Default to email prefix
    
    try {
      const { data: profile } = await supabase
        .from('user_profiles')
        .select('email')
        .eq('id', user.id)
        .single();
      
      if (profile?.email) {
        // Extract name from email or use email prefix
        userName = profile.email.split('@')[0];
      }
    } catch (profileError) {
      console.log('No user profile found, using email prefix');
    }

    // Create verification link if user needs to verify email
    let verificationLink;
    if (!user.email_confirmed_at) {
      // This would typically be generated by your auth system
      verificationLink = `https://whatthemenu.com/auth/verify?token=${user.confirmation_token}`;
    }

    // Generate welcome email
    const welcomeTemplate = emailTemplates.welcome(userName, verificationLink);
    
    const emailData = {
      to: [user.email],
      subject: welcomeTemplate.subject,
      html: welcomeTemplate.html,
      text: welcomeTemplate.text
    };

    // Send welcome email
    const emailResult = await emailService.sendEmail(emailData);

    // Log the email send
    await emailService.logEmailSend(
      supabase,
      'welcome_email',
      user.email,
      emailResult.success,
      emailResult.id,
      emailResult.error
    );

    if (!emailResult.success) {
      console.error('Failed to send welcome email:', emailResult.error);
      return {
        statusCode: 500,
        body: JSON.stringify({ 
          error: 'Failed to send welcome email',
          details: emailResult.error 
        }),
      };
    }

    return {
      statusCode: 200,
      body: JSON.stringify({ 
        success: true, 
        message: 'Welcome email sent successfully',
        emailId: emailResult.id
      }),
    };

  } catch (error) {
    console.error('Welcome email webhook error:', error);
    
    return {
      statusCode: 500,
      body: JSON.stringify({ 
        error: 'Internal server error',
        details: error instanceof Error ? error.message : 'Unknown error'
      }),
    };
  }
};

export { handler };