[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install --prefer-offline=false && npm run build"

[build.environment]
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200