# netlify.toml - Fixed version

[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install --prefer-offline=false && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

# Redirects for SPA routing and API proxy
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Function-specific settings
[functions]
  node_bundler = "esbuild"

# Headers for CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"