[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install --prefer-offline=false && npm run build"

[build.environment]
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers for CORS (for the API functions)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Redirect API calls to functions (optional - for cleaner URLs)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Keep your existing SPA redirect (this should be LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200